[tool.poetry]
name = "cryptopals"
version = "0.0.1"
description = "Attempt to solve the Cryptopals challenges"
authors = ["Bertrand Bonnefoy-Claudet <bertrand@bertrandbc.com>"]
license = "MIT"
packages = [
    {include = "cryptopals", from = "src"},
]

[tool.poetry.dependencies]
cryptography = "*"
python = "^3.7"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
flake8 = "*"
isort = "*"
mypy = "*"
pylint = "*"
pytest = "*"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
